name: redazul_transportador
description: "Versión de trazul para transportadores"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  flutter_holo_date_picker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  assets:
  - assets/ 
  - assets/images/

  fonts:
  - family: NunitoBold
    fonts:
      - asset: assets/fonts/nunito/Nunito-Bold.ttf
  - family: NunitoRegular
    fonts:
      - asset: assets/fonts/nunito/Nunito-Regular.ttf
  - family: NunitoSemibold
    fonts:
      - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
  - family: NunitoItalic
    fonts:
      - asset: assets/fonts/nunito/Nunito-Italic.ttf


  uses-material-design: true
